red: 
    task_and_robot_environment_name: 'RedMadoana-v0'
    ros_ws_abspath: "/home/nabesanta/red_RL"
    running_step: 0.04   # amount of time the control will be executed
    pos_step: 0.016   # increment in position for each command

    #qlearn parameters
    # α
    alpha: 0.5
    # ε
    epsilon: 0.9
    # γ
    gamma: 0.99

    epsilon_discount: 0.999
    n_episodes: 100
    n_steps: 5000
    running_step: 0.06   # time for each step
