red: 
    task_and_robot_environment_name: 'RedMadoana-v0'
    ros_ws_abspath: "/home/maedalab/red_RL"
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #qlearn parameters
    # α
    alpha: 0.1
    # ε
    epsilon: 0.9
    # γ
    gamma: 0.7

    epsilon_discount: 0.999
    n_episodes: 500
    n_steps: 500
    running_step: 0.06 # Time for each step
